# Generated by Django 5.0.6 on 2024-06-29 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.region')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_calle', models.CharField(max_length=255)),
                ('direccion_numero', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo')], max_length=10)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habitaciones', models.PositiveIntegerField()),
                ('banos', models.PositiveIntegerField()),
                ('estacionamiento_si_no', models.BooleanField(default=False)),
                ('estacionamiento_cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_uf', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.comuna')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.tipopropiedad')),
            ],
        ),
    ]
