# Generated by Django 5.0.6 on 2024-06-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_propiedad_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='id',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propiedad_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
