# Generated by Django 5.0.6 on 2024-06-30 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_remove_propiedad_id_propiedad_propiedad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='propiedades.region'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='region',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='propiedades.region'),
        ),
    ]
